; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
; framework = espidf
framework = arduino, espidf
monitor_speed = 115200
upload_speed = 921600

monitor_filters = esp32_exception_decoder


lib_deps =
  bodmer/TFT_eSPI@^2.5.32
  adafruit/Adafruit SSD1306
  lvgl/lvgl@^8.3.0
  ; https://github.com/lvgl/lvgl_esp32_drivers.git
  adafruit/Adafruit GFX Library
  Wire
  SPI


board_build.sdkconfig = sdkconfig.defaults


build_flags =
  -I./include
  -Ilib/lvgl/src
  -DLV_LVGL_H_INCLUDE_SIMPLE  
  -DCONFIG_LV_TFT_DISPLAY_CONTROLLER_ST7789
  -DDISABLE_ALL_LIBRARY_WARNINGS

